version: "2"

services:
  mpi_head:
    image: carlochess/openmpi
    ports: 
     - "22"
    volumes:
     - ./app:/app
  mpi_node: 
    image: carlochess/openmpi
    volumes:
     - ./app:/app

networks:
  default:
    external:
      name: uchuva-net
